name: catalog-ing
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyterlab=1.2.5
  - jupyter_client=5.3.1
  - nbserverproxy
  - netcdf4=1.5.1.1
  - metpy
  - numpy
  - climpred
  - cfgrib
  - scipy
  - xarray>=0.14.1
  - intake
  - intake-xarray
  - click
  - dask
  - xskillscore>=0.0.12
  - cartopy
  - matplotlib
  - tqdm
  - ipywidgets
  - pip:
